# SOBBH TDI-on-the-fly waveform generation (time domain)

# Copyright (C) 2026 Michael L. Katz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Optional

import numpy as np
from lisatools.response.tdionfly import TDTDIonTheFly
from lisatools.sources.sobbh.waveform import SOBBHWaveform

from .utils.parallelbase import BBHxParallelModule


class SOBBHTDIonFly(BBHxParallelModule):
    """Generate SOBBH TDI observables on the fly in the time domain.

    This is the **time-domain** SOBBH counterpart of
    :class:`bbhx.mbhtdionfly.MBHTDIonFly`. It feeds the SOBBH PN inspiral's
    amplitude/phase -- generated by the **same** waveform tool the legacy
    ``pyResponse`` path uses (:class:`lisatools.sources.sobbh.waveform.SOBBHWaveform`,
    via its :meth:`~lisatools.sources.sobbh.waveform.SOBBHWaveform.compute_amp_phase`)
    -- through the LISA TDI-on-the-fly response
    (:class:`lisatools.response.tdionfly.TDTDIonTheFly`). The legacy and
    on-the-fly responses therefore share an identical 3.5PN core and differ
    only in the projection (Lagrange-interpolated ``pyResponseTDI`` vs analytic
    on-the-fly delays on a cubic-spline amp/phase). This makes them directly
    comparable in the time domain.

    Unlike :class:`SOBBHTDIonTheFly` (the heterodyned frequency-domain path,
    which evaluates the PN amplitude/phase internally in C++ on a power-of-two
    sparse grid), this class produces the dense time-domain TDI exactly as
    :class:`MBHTDIonFly` does for MBHs.

    The amp/phase are splined on a **sparse** node grid (the SOBBH GW phase is
    smooth -- ``fdot`` is tiny -- so a cubic spline through a coarse grid
    reconstructs it to far below 1e-9 rad), while the TDI itself is evaluated
    on the **dense** output grid so the carrier is resolved in the result.

    Convention note. The on-the-fly response builds
    ``hSp = -amp (1+cos^2 i) cos(phase)`` and
    ``hSc = -amp (2 cos i) sin(phase)`` then rotates by ``psi``. With
    ``amp = A`` (intrinsic, no inclination) and ``phase = 2*Phi + pi`` this
    reproduces the legacy
    ``hp = A (1+cos^2 i) cos(2 Phi)`` / ``hx = A (2 cos i) sin(2 Phi)`` exactly,
    so -- in contrast to ``MBHTDIonFly`` which folds the inclination into the
    per-mode spherical harmonic and passes ``inc = 0`` -- the **real**
    inclination is passed to the response here.

    Args:
        wave_gen (:class:`SOBBHWaveform`): SOBBH PN waveform generator. Only its
            ``reference_time`` (the epoch at which ``f_low`` is defined) is used
            here; the amp/phase are evaluated on this class's own node grid via
            ``wave_gen.compute_amp_phase``.
        orbits (:class:`lisatools.detector.Orbits`): Configured orbits instance
            (load with ``frame="icrs"`` to consume ``(ra, dec)`` directly).
        tdi_config (:class:`lisatools.response.tdiconfig.TDIConfig`): TDI
            configuration (e.g. ``TDIConfig("2nd generation")``).
        dt (float): Sampling cadence of the data stream (sec).
        Tobs (float): Observation time (sec) -- used to build the default
            evaluation window when ``upsample_t_arr`` is not given at call time.
        t0 (float): Absolute start time of the default evaluation window (sec).
        n_grid (int, optional): Number of sparse amplitude/phase spline nodes.
            (default: ``2048``)
        buffer_time (float, optional): Seconds by which the amp/phase node grid
            is padded beyond the evaluation window on each side, giving the
            on-the-fly kernel light-travel-time headroom for its retarded-time
            reads. (default: ``5000.0``)
        force_backend (str, optional): ``"cpu"``, ``"gpu"``, ``"cuda"``,
            ``"cuda11x"``, ``"cuda12x"``, or ``"cuda13x"``. (default: ``None``)
    """

    def __init__(
        self,
        wave_gen: SOBBHWaveform,
        orbits,
        tdi_config,
        dt,
        Tobs,
        t0,
        n_grid: int = 2048,
        buffer_time: float = 5000.0,
        force_backend=None,
    ):
        super().__init__(force_backend=force_backend)
        self.wave_gen = wave_gen
        self.orbits = orbits
        self.tdi_config = tdi_config
        self.dt = dt
        self.T = Tobs
        self.t0 = t0
        self.n_grid = int(n_grid)
        self.buffer_time = float(buffer_time)

    @classmethod
    def supported_backends(cls) -> list:
        return ["bbhx_" + _tmp for _tmp in cls.GPU_RECOMMENDED()]

    @property
    def xp(self) -> object:
        """Numpy or Cupy."""
        return self.backend.xp

    @property
    def response_backend(self) -> str:
        """Backend flavor handed to the lisatools response classes."""
        return self.backend.name.split("_")[-1]

    @property
    def dt(self) -> float:
        """dt value from data."""
        return self._dt

    @dt.setter
    def dt(self, dt: float):
        self._dt = dt
        self.sampling_frequency = 1 / dt

    def __call__(
        self,
        m1,
        m2,
        s1,
        s2,
        distance,
        f_low,
        phi0,
        inc,
        ra,
        dec,
        psi,
        t_shift: float = 0.0,
        upsample_t_arr: np.ndarray = None,
        combine: bool = True,
        *args: Optional[tuple],
        **kwargs: Optional[dict],
    ):
        """Generate the time-domain SOBBH TDI observables.

        Args:
            m1, m2 (float): component masses (solar masses).
            s1, s2 (float): dimensionless aligned spins.
            distance (float): luminosity distance (Gpc).
            f_low (float): GW frequency at the reference epoch (Hz).
            phi0 (float): orbital phase at the reference epoch (rad) -- the
                catalogue ``TrueAnomaly``.
            inc (float): inclination (rad).
            ra, dec (float): sky position consumed in the orbits frame
                (ICRS when the orbits are loaded with ``frame="icrs"``).
            psi (float): polarization (rad).
            t_shift (float, optional): extra time offset (sec). (default: 0)
            upsample_t_arr (np.ndarray, optional): absolute times on which to
                return the TDI. Defaults to ``arange(N)*dt + t0`` covering
                ``[t0, t0 + Tobs]``.
            combine (bool, optional): sum over the (single) sub-signal axis so
                the return shape is ``(3, len(upsample_t_arr))``. (default:
                ``True``)

        Returns:
            np.ndarray: TDI observables, ``(3, N)`` if ``combine`` else
            ``(1, 3, N)``.
        """
        xp = self.xp

        if upsample_t_arr is None:
            n = int(round(self.T / self.dt))
            upsample_t_arr = xp.arange(n) * self.dt + self.t0
        upsample = xp.asarray(upsample_t_arr)

        lo = float(upsample.min().item())
        hi = float(upsample.max().item())

        # Sparse node grid for the (smooth) amplitude/phase splines, padded
        # beyond the data window so the on-the-fly retarded-time reads stay in
        # range.
        node_times = np.linspace(
            lo - self.buffer_time, hi + self.buffer_time, self.n_grid
        )

        # Same SOBBH PN tool the legacy pyResponse path uses, in its amp/phase
        # representation: A (intrinsic, no inclination) and the GW phase 2*Phi.
        abs_t, gw_amp, gw_phase = self.wave_gen.compute_amp_phase(
            m1, m2, s1, s2, distance, f_low, phi0, times=node_times, t_shift=t_shift
        )

        amp = xp.asarray(gw_amp)[None, :]
        # phase = 2*Phi + pi reproduces the legacy hp/hx signs under the
        # response's hSp = -amp (1+cos^2 i) cos(phase) convention.
        phase = xp.asarray(gw_phase + np.pi)[None, :]
        t_input = xp.asarray(abs_t)[None, :]

        # Dense evaluation grid (carrier-resolved) for the output TDI spline,
        # kept inside the node grid's safe interior for kernel delay headroom.
        eval_lo = float(t_input.min().item()) + self.buffer_time
        eval_hi = float(t_input.max().item()) - self.buffer_time
        n_eval = int((eval_hi - eval_lo) / self.dt) + 1
        eval_t = (eval_lo + xp.arange(n_eval) * self.dt)[None, :]

        tdi_gen = TDTDIonTheFly(
            eval_t,
            amp,
            phase,
            sampling_frequency=self.sampling_frequency,
            num_sub=1,
            t_input=t_input,
            tdi_config=self.tdi_config,
            orbits=self.orbits,
            force_backend=self.response_backend,
        )

        # Real inclination + polarization: amp is intrinsic, so get_hp_hc
        # applies the (1+cos^2 i) / 2 cos i factors and the psi rotation.
        inc_arr = xp.full(1, inc)
        psi_arr = xp.full(1, psi)
        ra_arr = xp.full(1, ra)
        dec_arr = xp.full(1, dec)

        output = tdi_gen(inc_arr, psi_arr, ra_arr, dec_arr, return_spline=True)

        new_tdi = xp.zeros((output.t_arr.shape[0], 3, upsample.shape[-1]))
        keep = (upsample >= output.t_arr.min().item()) & (
            upsample <= output.t_arr.max().item()
        )
        new_tdi[:, :, keep] = output.eval_tdi(upsample[keep])

        if combine:
            return new_tdi.sum(axis=0)

        return new_tdi
